### PR TITLE
Correcting condition to read team configuration file.

### PR DESCRIPTION
**Pull request by chinmdas**
**What It Does**
It does a correct condition checking on whether or not Team Configuration File exists.

**How to Test**

- click on + icon 
- Click on "Create a New CICS Profile"
- zowe.config.json file opens up

**Review Checklist**
I certify that I have:
- [ ] tested my changes
- [ ] added/updated automated tests
- [ ] updated the changelog
- [ ] followed the [contribution guidelines](https://github.com/zowe/zowe-cli/blob/master/CONTRIBUTING.md)

**Additional Comments**

- Currently, these changes only take care of the condition when a Team Configuration file is available globally.
- Still investigating the case when Team Configuration file is missing,

### CODE REVIEW

**Review by zFernand0 — APPROVED** [review]
LGTM! 😋

**Comment by zFernand0** [comment]
Hey @chinmdas,
Could you add a quick changelog entry for this fix? 🙏 
- https://github.com/zowe/zowe-cli/blob/master/CONTRIBUTING.md#changelog-update-guidelines

**Comment by chinmdas** [comment]
Hi @JillieBeanSim , Can I get your review on this?

**Comment by zFernand0** [comment]
My apologies for the delay.
@JillieBeanSim 
If you have a chance to test this, that would be great.
If not, the CICS monorepo doesn't require 2 approvals at the moment, so we can get this merged and published right away 🙏

**Comment by zFernand0** [comment]
Will publish this with:
- #161

**Comment by davenice** [comment]
This is a partial fix for #33

**Pull request merged**
